### ISSUE TITLE
Token update lost between GS and Client

### ISSUE THREAD

**Issue by aeturch** [NetwSec/Phase2#3]
The issue is in the "auth" branch, which implements token authentication.

GS addgroupCallback adds a new group by adding the ownership in the UserList, gets the correct new token, signs the new token and adds it to the Response it sends to the Client.
However, the token the Client receives has the contents of the old token (not containing the new group).
Authentication fails on anything to do with this group until the user logs out and back in (thereby getting a fresh token loaded from the UserList with all correct groups).

Screenshot of GS output:

> ![screen shot 2016-04-24 at 4 37 15 pm](https://cloud.githubusercontent.com/assets/5882640/14770632/823ef562-0a3b-11e6-9eaa-802f6492be3d.png)

The first signing message is when the token is issued. The second is when the new group is added. It correctly contains the name of the new group.
The message after that shows that addgroupCallback adds the token with correct contents to the Response.

Screenshot of Client output when adding a group:

> ![screen shot 2016-04-24 at 4 37 48 pm](https://cloud.githubusercontent.com/assets/5882640/14770634/823f8e82-0a3b-11e6-87f0-46d608b42da1.png) 

After the group is added, the token the Client extracts from the GS Response contains the old contents.

Screenshot of Client output when subsequently trying to list members of the group:

> ![screen shot 2016-04-24 at 4 37 57 pm](https://cloud.githubusercontent.com/assets/5882640/14770633/823f55c0-0a3b-11e6-87dc-5879b76cc914.png)

Obviously, it gets the token from Client so it has the old contents. Authentication fails.

**Comment by aeturch** [comment]
I also tried changing everything of type UserToken to type UserTokenImp just to eliminate the possibility of weird casting issues. It didn't change anything for me.

**Comment by MakiseKurisu** [comment]
Thoughts after reading the code so far:
1. Authentication should be put in ServerFramework as almost every operation requires it (except login).
2. Authentication shouldn't have anything to do with the token content.
